### ISSUE TITLE
Rebuild user login 

### ISSUE THREAD

**Issue by Brofian** [edelmaenner/edelgames#10]
The current user login is make by accessing the default login form of the homepage and parsing the html response. This should be rebuild to use the now available login API from @Zweistein2 

API URL: https://edelmaenner.net/edelgames/authenticate
-> 5 min timeout after failing authentication 5 times

Send POST Request to the API with the following content:
```
{
  "login": "benutzername",
  "password": "supergeheimespasswort",
  "xenforo_token": "secretTokenXF123456"
}
```
(Either password or xenforo_token has to be transmitted)

Response on failure:
```
{
    "login_sucessful": "false"
}
```
(or html, which should be catched while parsing the JSON)

Response on success:
```
{
    "login_sucessful": "true",
    "xenforo_token": "secretTokenXF123456",
    "minecraft_name": "benutzername",
    "user_id": 123456,
    "group_id": 123,
    "custom_title": "Mein toller Benutzer-Titel"
}
```

**Comment by kid2407** [comment]
Current state can be found in [kid2407/edelgames:feature/rebuild-user-login](https://github.com/kid2407/edelgames/tree/feature/rebuild-user-login)
