### ISSUE TITLE
Add proper logging

### ISSUE THREAD

**Issue by kid2407** [edelmaenner/edelgames#18]
At the moment logging works over one function that does the job, but isn't really obvious to find nor that simple to use.

Because of this I suggest the following in regards to logging:

## Log Format:

All logging should follow the same format, using the [ISO 8601 Standard](https://de.m.wikipedia.org/wiki/ISO_8601) for dates. The format used will be the following:
```
[ISO 8601 Date][Section, e.g. "System", "StadtLandFluss" etc.][Log level] Message to be logged
```
 Filled with data it looks like this:
```
[2022-12-24 23:23:59][System][INFO] User abcd123 authenticated successfully as "xxJohnnyxx"
```

## Log Levels

The log level to use should be configured in the `.env` files for frontend and backend. All log statements that are at least as "important" as the selected log level will be printed when called. The available log levels will be: ERROR, WARNING, INFO and DEBUG.

## Logger classes / instances

There should be a global logger to use if no specific version is available, as well as pre-configured ones for e.g. modules using the modules ID in the log.
A logger should have the following methods, each corresponding to the different log levels: `error`, `warning`, `info` and `debug`, as well as a parameter to supply on creation to set the section, which otherwise defaults to` "SYSTEM".`
Loggers for modules can be easily implemented via using the `ModuleGameApi` class they alll extend.

**Comment by Brofian** [comment]
Merged
