### ISSUE TITLE
onUserJoin-event bugged

### ISSUE THREAD

**Issue by Zweistein2** [edelmaenner/edelgames#25]
The onUserJoin-event is currently triggered in the backend as soon as the room change has been completed in the backend. At this point, however, the UI is not yet ready to receive or process events (because the event handlers are not yet registered).

Solution:
After mounting the UI, send an event to the backend to signal readiness for event handling. The backend can only send the onUserJoin event AFTER this event.

**Comment by Brofian** [comment]
Alternative: Receive Events in the frontend inside a singleton, that stores the events for a set amount of time and calls a new listener with these events after its registration

**Comment by Brofian** [comment]
By now, there were two changes that will prevent this from happening:
- prevent users from joining a running game (this would be more effort that it's worth anyway) 
- events are buffered until there is a listener to handle these (5 seconds for system events, 15 seconds for game events)
